### PR TITLE
Windows support (find idris.exe on windows)

### PR DESCRIPTION
**Pull request by Cynede**

### CODE REVIEW

**Comment by david-christiansen** [comment]
@archaeron tested it on Windows without this change and reported that it worked - could this be a difference in Windows versions?

**Comment by Cynede** [comment]
@david-christiansen it doesn't find just "idris" for me there, win 10 64 bit racket 6.2

**Comment by david-christiansen** [comment]
Well, I think we should have this then!

**Comment by david-christiansen** [comment]
Thanks!

**Comment by archaeron** [comment]
@david-christiansen I tested it with windows, but hardcoded the path. Sorry, forgot to tell you. It worked well apart from that :)

**Comment by david-christiansen** [comment]
Everything makes sense now :-)

**Pull request merged**
